
-- Day 2 – Constraints, Sample Data & Queries

-- ✅ 1. Add Indexes
CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_hotel ON users(hotel_id);
CREATE INDEX idx_bill_created_at ON bills(created_at);

-- ✅ 2. Insert Sample Hotels
INSERT INTO hotels (name, address) VALUES 
('Taj Palace', 'Delhi'),
('The Oberoi', 'Mumbai'),
('Leela Palace', 'Bangalore');

-- ✅ 3. Insert Sample Users
INSERT INTO users (username, password, role, hotel_id) VALUES 
('admin1', 'adminpass1', 'ADMIN', 1),
('staff1', 'staffpass1', 'STAFF', 1),
('admin2', 'adminpass2', 'ADMIN', 2),
('staff2', 'staffpass2', 'STAFF', 2);

-- ✅ 4. Insert Sample Products
INSERT INTO products (name, price, hotel_id) VALUES 
('Paneer Butter Masala', 250.00, 1),
('Veg Biryani', 180.00, 1),
('Chicken Curry', 300.00, 2),
('Naan', 40.00, 2);

-- ✅ 5. Insert Sample Bills
INSERT INTO bills (created_at, hotel_id, user_id) VALUES 
('2025-06-01 12:00:00', 1, 1),
('2025-06-02 18:30:00', 1, 2),
('2025-06-03 13:15:00', 2, 3);

-- ✅ 6. Insert Sample Bill Items
INSERT INTO bill_items (quantity, bill_id, product_id) VALUES 
(2, 1, 1),  -- 2 x Paneer Butter Masala
(1, 1, 2),  -- 1 x Veg Biryani
(3, 2, 1),  -- 3 x Paneer Butter Masala
(2, 3, 3),  -- 2 x Chicken Curry
(4, 3, 4);  -- 4 x Naan

-- ✅ 7. Query: Fetch Products by Hotel
-- Get all products for hotel_id = 1
SELECT * FROM products WHERE hotel_id = 1;

-- ✅ 8. Query: Total Bill Amount in a Date Range
-- Calculate total for bills from 1st June to 4th June 2025
SELECT b.id AS bill_id, SUM(p.price * bi.quantity) AS total_amount
FROM bills b
JOIN bill_items bi ON b.id = bi.bill_id
JOIN products p ON bi.product_id = p.id
WHERE b.created_at BETWEEN '2025-06-01' AND '2025-06-04'
GROUP BY b.id;

-- ✅ 9. Query: Bills by Specific User
-- Bills generated by user_id = 1
SELECT * FROM bills WHERE user_id = 1;

-- ✅ 10. MySQL Dump Instruction (not SQL, command-line)
-- Run this in terminal to generate dump:
-- mysqldump -u root -p hotel_billing > hotel_billing_dump.sql
